// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inv_alr_cpp
Rcpp::NumericVector inv_alr_cpp(const Rcpp::NumericVector& alr_coords);
RcppExport SEXP _SDDGP_inv_alr_cpp(SEXP alr_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alr_coords(alr_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_alr_cpp(alr_coords));
    return rcpp_result_gen;
END_RCPP
}
// alr_cpp
Rcpp::NumericVector alr_cpp(const Rcpp::NumericVector& theta);
RcppExport SEXP _SDDGP_alr_cpp(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(alr_cpp(theta));
    return rcpp_result_gen;
END_RCPP
}
// precompute_log_factorial
std::vector<double> precompute_log_factorial(int max_value);
RcppExport SEXP _SDDGP_precompute_log_factorial(SEXP max_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_value(max_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_log_factorial(max_value));
    return rcpp_result_gen;
END_RCPP
}
// log_lik_nb_cpp
double log_lik_nb_cpp(const Rcpp::IntegerVector& y, const Rcpp::NumericVector& mu, double phi, const std::vector<double>& log_factorial_cache);
RcppExport SEXP _SDDGP_log_lik_nb_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP, SEXP log_factorial_cacheSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type log_factorial_cache(log_factorial_cacheSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_nb_cpp(y, mu, phi, log_factorial_cache));
    return rcpp_result_gen;
END_RCPP
}
// dirichlet_prior_cpp
double dirichlet_prior_cpp(const Rcpp::NumericVector& theta, const Rcpp::NumericVector& alpha);
RcppExport SEXP _SDDGP_dirichlet_prior_cpp(SEXP thetaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(dirichlet_prior_cpp(theta, alpha));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_deconv_cpp
Rcpp::List mcmc_deconv_cpp(const Rcpp::IntegerVector& y, const Rcpp::NumericMatrix& ref, const Rcpp::NumericVector& alpha, double a_phi, double b_phi, int n_iter, int burn_in, double theta_proposal_sd, double phi_proposal_sd, int adapt_period, double target_accept, int thin, bool early_stop, double rhat_threshold, int min_post_samples, int convergence_check_interval);
RcppExport SEXP _SDDGP_mcmc_deconv_cpp(SEXP ySEXP, SEXP refSEXP, SEXP alphaSEXP, SEXP a_phiSEXP, SEXP b_phiSEXP, SEXP n_iterSEXP, SEXP burn_inSEXP, SEXP theta_proposal_sdSEXP, SEXP phi_proposal_sdSEXP, SEXP adapt_periodSEXP, SEXP target_acceptSEXP, SEXP thinSEXP, SEXP early_stopSEXP, SEXP rhat_thresholdSEXP, SEXP min_post_samplesSEXP, SEXP convergence_check_intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type a_phi(a_phiSEXP);
    Rcpp::traits::input_parameter< double >::type b_phi(b_phiSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< double >::type theta_proposal_sd(theta_proposal_sdSEXP);
    Rcpp::traits::input_parameter< double >::type phi_proposal_sd(phi_proposal_sdSEXP);
    Rcpp::traits::input_parameter< int >::type adapt_period(adapt_periodSEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< bool >::type early_stop(early_stopSEXP);
    Rcpp::traits::input_parameter< double >::type rhat_threshold(rhat_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_post_samples(min_post_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type convergence_check_interval(convergence_check_intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_deconv_cpp(y, ref, alpha, a_phi, b_phi, n_iter, burn_in, theta_proposal_sd, phi_proposal_sd, adapt_period, target_accept, thin, early_stop, rhat_threshold, min_post_samples, convergence_check_interval));
    return rcpp_result_gen;
END_RCPP
}
// spatial_interpolate_theta_cpp
Rcpp::NumericMatrix spatial_interpolate_theta_cpp(const Rcpp::NumericMatrix& theta_observed, const Rcpp::NumericMatrix& coords_observed, const Rcpp::NumericMatrix& coords_new, double bandwidth, int n_neighbors, double nu);
RcppExport SEXP _SDDGP_spatial_interpolate_theta_cpp(SEXP theta_observedSEXP, SEXP coords_observedSEXP, SEXP coords_newSEXP, SEXP bandwidthSEXP, SEXP n_neighborsSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type theta_observed(theta_observedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords_observed(coords_observedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords_new(coords_newSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_interpolate_theta_cpp(theta_observed, coords_observed, coords_new, bandwidth, n_neighbors, nu));
    return rcpp_result_gen;
END_RCPP
}
// cosine_similarity_matrix_cpp
Rcpp::NumericMatrix cosine_similarity_matrix_cpp(const Rcpp::NumericMatrix& A, const Rcpp::NumericMatrix& B);
RcppExport SEXP _SDDGP_cosine_similarity_matrix_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_similarity_matrix_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// constrained_nnls_spot_cpp
Rcpp::NumericVector constrained_nnls_spot_cpp(const Rcpp::NumericVector& y_spot, const Rcpp::NumericMatrix& X_cells, const Rcpp::NumericVector& budget, const Rcpp::IntegerVector& type_assign, double lambda_reg, int max_iter);
RcppExport SEXP _SDDGP_constrained_nnls_spot_cpp(SEXP y_spotSEXP, SEXP X_cellsSEXP, SEXP budgetSEXP, SEXP type_assignSEXP, SEXP lambda_regSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_spot(y_spotSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X_cells(X_cellsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type budget(budgetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type type_assign(type_assignSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_reg(lambda_regSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(constrained_nnls_spot_cpp(y_spot, X_cells, budget, type_assign, lambda_reg, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SDDGP_inv_alr_cpp", (DL_FUNC) &_SDDGP_inv_alr_cpp, 1},
    {"_SDDGP_alr_cpp", (DL_FUNC) &_SDDGP_alr_cpp, 1},
    {"_SDDGP_precompute_log_factorial", (DL_FUNC) &_SDDGP_precompute_log_factorial, 1},
    {"_SDDGP_log_lik_nb_cpp", (DL_FUNC) &_SDDGP_log_lik_nb_cpp, 4},
    {"_SDDGP_dirichlet_prior_cpp", (DL_FUNC) &_SDDGP_dirichlet_prior_cpp, 2},
    {"_SDDGP_mcmc_deconv_cpp", (DL_FUNC) &_SDDGP_mcmc_deconv_cpp, 16},
    {"_SDDGP_spatial_interpolate_theta_cpp", (DL_FUNC) &_SDDGP_spatial_interpolate_theta_cpp, 6},
    {"_SDDGP_cosine_similarity_matrix_cpp", (DL_FUNC) &_SDDGP_cosine_similarity_matrix_cpp, 2},
    {"_SDDGP_constrained_nnls_spot_cpp", (DL_FUNC) &_SDDGP_constrained_nnls_spot_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SDDGP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
