# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv_alr_cpp <- function(alr_coords) {
    .Call(`_SDDGP_inv_alr_cpp`, alr_coords)
}

alr_cpp <- function(theta) {
    .Call(`_SDDGP_alr_cpp`, theta)
}

precompute_log_factorial <- function(max_value) {
    .Call(`_SDDGP_precompute_log_factorial`, max_value)
}

log_lik_nb_cpp <- function(y, mu, phi, log_factorial_cache) {
    .Call(`_SDDGP_log_lik_nb_cpp`, y, mu, phi, log_factorial_cache)
}

dirichlet_prior_cpp <- function(theta, alpha) {
    .Call(`_SDDGP_dirichlet_prior_cpp`, theta, alpha)
}

mcmc_deconv_cpp <- function(y, ref, alpha, a_phi = 1.0, b_phi = 1.0, n_iter = 5000L, burn_in = 2000L, theta_proposal_sd = 0.05, phi_proposal_sd = 0.1, adapt_period = 500L, target_accept = 0.234, thin = 1L, early_stop = FALSE, rhat_threshold = 1.05, min_post_samples = 100L, convergence_check_interval = 200L) {
    .Call(`_SDDGP_mcmc_deconv_cpp`, y, ref, alpha, a_phi, b_phi, n_iter, burn_in, theta_proposal_sd, phi_proposal_sd, adapt_period, target_accept, thin, early_stop, rhat_threshold, min_post_samples, convergence_check_interval)
}

spatial_interpolate_theta_cpp <- function(theta_observed, coords_observed, coords_new, bandwidth, n_neighbors, nu = 1.5) {
    .Call(`_SDDGP_spatial_interpolate_theta_cpp`, theta_observed, coords_observed, coords_new, bandwidth, n_neighbors, nu)
}

cosine_similarity_matrix_cpp <- function(A, B) {
    .Call(`_SDDGP_cosine_similarity_matrix_cpp`, A, B)
}

constrained_nnls_spot_cpp <- function(y_spot, X_cells, budget, type_assign, lambda_reg = 0.01, max_iter = 200L) {
    .Call(`_SDDGP_constrained_nnls_spot_cpp`, y_spot, X_cells, budget, type_assign, lambda_reg, max_iter)
}

